### ISSUE TITLE
Ignore directories/files?

### ISSUE THREAD

**Issue by jcabreram** [a7ex/xcresultparser#10]
Is it possible to ignore specific directories/files? I'm currently using the parser for a Swift package and the parser is including in the results the files in ~/Library/Developer/Xcode/DerivedData which are coming from other package dependencies for which I'm not interested in their code coverage.

Thank you for this awesome project, it's been really useful.

**Comment by a7ex** [comment]
Hello Jonathan,
sorry for the late response.
Is it enough to specify the targets which you are interested in?
There is an option to specify the targets, for which the code coverage report is generated.
You should also be able to specify the targets for the coverage for your test run, so that the data doesn't even appear in the xcresult file.

But meanwhile you may want to look into the option "t":

  -t, --coverage-targets <coverage-targets>
                          Specify which targets to calculate coverage from

Would that help your problem?

**Comment by jcabreram** [comment]
Hi @a7ex, thank you very much for your reply. I've tried to specify the targets so that the data doesn't even appear in the `.xcresult` file but because it's a Swift package that I'm testing without converting it into an `.xcodeproj`, it doesn't seem to be possible to do that, as I've also read on [this Swift forum thread](https://forums.swift.org/t/gather-coverage-for-some-targets-with-swift-packages/31142/3).

I'm generating the `.xcresult` file with the command `xcodebuild -scheme MyScheme test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' -enableCodeCoverage YES`

I've tried the `-t` option of `xcresultparser` as you've suggested but it's still showing the dependencies in its output starting with `Users.runner.Library.Developer.Xcode.DerivedData.s-budpulsgqbxhygedafjqfylpodyj.SourcePackages.checkouts`. 

This is the command I'm using for parsing: `xcresultparser -t MyScheme -o cobertura coverage.xcresult > cobertura.xml`

Am I doing something incorrectly?

Thanks again!

**Comment by a7ex** [comment]
The targets option should do what you want.
Could you send me an example xcarchive so I can check why the targets filter doesn't work?

**Comment by jcabreram** [comment]
Sure, here's the example xcarchive. Thank you for looking into this @a7ex!
[coverage.xcresult.zip](https://github.com/a7ex/xcresultparser/files/10689376/coverage.xcresult.zip)

**Comment by a7ex** [comment]
Hi @jcabreram 
thanks for the example file.
It turned out, that the -t option was not yet used in the coverage methods.
Please try the new version 1.3 I just released.

Hope it fixes your issue. Sorry for the delay.

**Comment by jcabreram** [comment]
@a7ex thank you so so much! That worked. I'm only seeing the code coverage for the target now.
