### ISSUE TITLE
Json format output

### ISSUE THREAD

**Issue by alexnot95** [a7ex/xcresultparser#14]
First of all thanks for the great project! 
It would be nice if it's possible to add json format to output type since we are using xcresult summaries in slack report messages, so It would be much easier if the whole summary data would be in json format, cuz it's easier to work with this format later :)

**Comment by a7ex** [comment]
Which one do you want in json format, coverage or test results and how would such a json format look like?

**Comment by a7ex** [comment]
Ok, that seems possible. I will have a closer look later.

**Comment by a7ex** [comment]
This is not an issue, but rather a feature request.
"It is easier for you to work with" is not a very strong reason for me to do the work for you for free.
