### ISSUE TITLE
Skipped tests shows as failed in txt results

### ISSUE THREAD

**Issue by alexnot95** [a7ex/xcresultparser#15]
We have a testplan with ~17 configurations (the difference between configurations are system region + system language) we use it to perform visual testing on different locales. Some of the tests are disabled:
example:
```
func testOne() throws {
throw XCTSkip("Disabled")
}
```

In txt report I see that skipped tests shows as failed on different locales, but I assume they should be excluded from the report and shouldn't be recognized as failed tests

the command I used to generate txt report is: 
xcresultparser -o txt -s failed -f result.xcresult > results.txt

**Comment by a7ex** [comment]
Would it be possible to send me the xcresult file, so I can see what's going on,  fix the issue and check the fix?

**Comment by alexnot95** [comment]
> Would it be possible to send me the xcresult file, so I can see what's going on, fix the issue and check the fix?

Yeah, I can send it on your email?

**Comment by a7ex** [comment]
Yes. please.

**Comment by alexnot95** [comment]
@a7ex file sent

**Comment by a7ex** [comment]
This looks like a duplicate of the other issue you opened.
To me it looks like XcresultKit is not interpreting the xcresult file, as you would expect it. There is nothing I can do about it. Sorry.
