### ISSUE TITLE
Wrong calculation of failed tests in txt results

### ISSUE THREAD

**Issue by alexnot95** [a7ex/xcresultparser#16]
We have a testplan with ~17 configurations (the difference between configurations are system region + system language) we use it to perform visual testing on different locales, also we've added 2 native retries in testplan configuration. I made some changes to fail 1 test on 2 locales. 
And after generation txt result with this command: 
xcresultparser -o txt -s failed -f result.xcresult > results.txt

I see in Summary 4 failed tests, but I assume that number should be 2, because other 2 it's just a retries, so the correct number should be 2 failed.

**Comment by alexnot95** [comment]
Hi @a7ex I've sent xcresult file to your email: kiki@farbflash.de

**Comment by a7ex** [comment]
that is the data I receive from XcresultKit.
There is not much I can do about that.
