### ISSUE TITLE
Corrupted data in txt results if run UI tests simultaneously on two devices

### ISSUE THREAD

**Issue by alexnot95** [a7ex/xcresultparser#17]
If run tests simultaneously on 2 devices for example we run tests on iPhone + iPad simultaneously, and as I understood the xcresult structure will be different from the run on 1 device, so txt results will be corrupted (it contains wrong failed tests count + doesn't contain any data about failed tests and locales)

<img width="806" alt="Screenshot 2023-05-16 at 17 07 16" src="https://github.com/a7ex/xcresultparser/assets/37154209/49a0cc63-df8a-481e-b011-6731a3b7015d">

and txt result after run the command: xcresultparser -o txt -s failed -f result.xcresult > results.txt
<img width="607" alt="Screenshot 2023-05-16 at 17 09 19" src="https://github.com/a7ex/xcresultparser/assets/37154209/c8490078-63b8-424f-a6cf-652fd127aa8f">

**Comment by alexnot95** [comment]
Hi @a7ex sent you xcresult file with such structure for debugging

**Comment by alexnot95** [comment]
> Hi Alexey, thanks. But please bear with me, that I do have a day job, which has precedence. As soon as I have some spare time, I will look into it. But you must also understand, that this is a side project and that I can not solve all your problems. This is an open source project and you are of course very welcome to contribute changes or even fix bugs yourself and create a PR.

yeah, got it, thank you anyway

**Comment by a7ex** [comment]
Thank you for being considerate

**Comment by a7ex** [comment]
I looked into the issue.
I am not getting any data from XcresultKit for your xcresult file.
xcresultparser is just a wrapper around XcresultKit (https://github.com/davidahouse/XCResultKit)
If I don't get data from XcresultKit, there is nothing I can do about it.
