### ISSUE TITLE
fullpath is not shown in xml

### ISSUE THREAD

**Issue by EaseTheWorld** [a7ex/xcresultparser#18]
When I run `xcresultparser -o xml Test-logging.xcresult`
output is like below.
```
<?xml version="1.0" encoding="UTF-8"?>
<testExecutions version="1">
    <file path="LoggingTests">
        <testCase name="testWhenSuccess()" duration="5"/>
        <testCase name="testWhenFailure()" duration="17"/>
    </file>
</testExecutions>
```
but when I passed this to sonar-scanner, it wasn't processed.
because sonar-scanner expects,
` <file path="Full/Path/LoggingTests.swift">`
https://docs.sonarqube.org/latest/analyzing-source-code/test-coverage/generic-test-data/#generic-test-execution

Is it possible to put the fullpath info here?

**Comment by a7ex** [comment]
Yes, it should be possible. Unfortunately the paths in the xcresult file are absolut and it is not easy to figure out the relative path names. Sonar however requires the relative paths.
In order for the xcresultparser to figure out how to convert to relative paths you need to pass the root directory as parameter. Then the paths can be converted.

**Comment by a7ex** [comment]
Oh maybe I remember wrong and mixed up requirements.

Read the chapter "About paths for the sonarqube scanner" at the end of the Readme. For me that works with sonarqube.

**Comment by EaseTheWorld** [comment]
I read the chapter but it is two different things to me.

1. "_The tools to get the data from the xcresult archive yield absolute path names._" -> result will look like `<file path="Full/Path/LoggingTests.swift">`.
2. "_the .xcresult bundle only lists the test by testclass, but not by file._" -> result will look like `<file path="LoggingTests">`

My case is 2. but you're saying 1.
For 1, I can use for sonarqube by replacing some path absolute->relative.
but For 2, I can't do anything about it because I don't have any info about directory.

Am I missing something? or my xcresult file is wrong?(I'm using XCode 14.3, MacOS 13.2)

**Comment by a7ex** [comment]
I will look into it, whether xcresult changed lately in this regard. We use the sonar scanner as well with our project and there we can see the tests.
I will see, what I can find out.

**Comment by EaseTheWorld** [comment]
Thank you for check.
Then xcresult never provides full path but only classname, and you've
grepped to get fullpath and pass to sonarqube?

or it depends on xcode version?

2023년 5월 19일 (금) 오후 9:46, alex da franca ***@***.***>님이 작성:

**Comment by a7ex** [comment]
Yes, that's exactly what xcresultparser does. The xcresult file provides the name of the test class and xcresultparser greps in the provided project folder for swift files which contain the string 'class name-of-the-testclass'
(I just realised, that what I did in my last response got chopped by GitHub, where I used 'opening-bracket' name-of-test-class 'closing-bracket').
That is a rather "naive" approach and it will break easily, but as far as my research goes, it is the only tool, which converts xcresult files to expose the tests to SonarQube due to this "dirty trick".

**Comment by a7ex** [comment]
If you do not run the SonarQube command line tool in the source folder of your project, but rather only have the xcresult file, there is not much I can do about it. The sonarqube command line tool needs to run in the sources folder where the tests are, which created the xcresult. It needs to scan the test files themselves.

**Comment by EaseTheWorld** [comment]
I looked into the logic and found `ActionTestableSummary` includes `projectRelativePath`, ex. Module1/Domain1/Module1Domain1.xcodeproj
I think this can optimize the grep logic by narrowing the search scope. especially for multi-module project.

**Comment by a7ex** [comment]
Thanks for the hint. I will look into that.
