### ISSUE TITLE
Why need to get the dtd file by visiting http://cobertura.sourceforge.net ? 

### ISSUE THREAD

**Issue by kieoo** [a7ex/xcresultparser#19]
If the cobertura.sourceforge.net server is down, the tool will fatalError
Why not back up a local dtd file to avoid this problem ?  @fadookie 

https://github.com/a7ex/xcresultparser/blob/205604b04a684ef7c6026e01f02efffc8d9987db/Sources/xcresultparser/CoberturaCoverageConverter.swift#L46

**Comment by fadookie** [comment]
This is working fine for me and seems to be a common practice when referencing a DTD. You are welcome to make a PR to use a cached copy of the DTD if you want.

**Comment by a7ex** [comment]
I made 1.4.2 with this change. Just because I tend to avoid fatalError()
