### ISSUE TITLE
Any chance of getting xcresultparser on brew?

### ISSUE THREAD

**Issue by weibel** [a7ex/xcresultparser#2]
I'm evaluating a few options for producing html from xcresult bundles and xcresultparser is one of them.
I just want to ask if you have considered publishing the library on Homebrew? It would make a CI setup a lot easier.
Thanks

**Comment by a7ex** [comment]
Hi Kaspar,
I haven't thought of it, but I am open for it any time. Will look into it and what's involved.

**Comment by a7ex** [comment]
You can now use:
```
brew tap a7ex/homebrew-formulae
brew install xcresultparser
```
