### ISSUE TITLE
Release: 1.6.0

### ISSUE THREAD

**Issue by Brett-Best** [a7ex/xcresultparser#29]
I see that `release/1.6.0` was merged into `main` - should a GitHub release + tag be made for it now?

**Comment by a7ex** [comment]
Good that I didn't make a release yet :-)
Thanks for taking the time to test, Brett. That is very much appreciated. Looks like 18446744073709551432 is beyond the Max Integer :-)
I might just need to convert it from Int to Double. Not sure where, however. Do you really have a xcresult, where one line is covered 18446744073709551432 times?

**Comment by Brett-Best** [comment]
Definitely not, I'm not sure where this number is coming from.

**Comment by Brett-Best** [comment]
WIll do would you be able to join https://ios-developers.io (Slack) or I can email it to you?
https://join.slack.com/t/ios-developers/shared_invite/zt-27swvfuqf-Onx~Oaywirk6G1pkuJWrNQ

**Comment by Brett-Best** [comment]
Confirm that for a few files, that number does appear for the execution count in the JSON given by the command above.

**Comment by a7ex** [comment]
I created a new pull request which fixes the issue. You already tested it and so I'll close this issue now
