### ISSUE TITLE
The coverage targets option is ignored for xml and cobertura output format

### ISSUE THREAD

**Issue by mwhrtin** [a7ex/xcresultparser#44]
With xcresultparser 1.7.2 the coverage targets are ignored when using the output formats xml and cobertura.

Output the results to standard out will correctly filter the results:
`xcresultparser -t MyScheme -o cli coverage.xcresult`

Output to xml or cobertura format will include all targets even when the -t option is used:
`xcresultparser -t MyScheme -o xml coverage.xcresult`

In my case this means that the results include checked out dependencies from the derived data folder which basically increases the file size of the resulting file 10x. 

Looking at the source code it doesn't look like `CoberturaCoverageConverter` or `SonarCoverageConverter` are using the given coverage targets at all. Is this an unwanted side effect after migrating to the new version of the `xccov` command-line tool since this appears to have been working in previous versions?

Perhaps and alternative could be to allow files or paths to be ignored, similar to what was originally suggested in https://github.com/a7ex/xcresultparser/issues/10?

**Comment by mwhrtin** [comment]
I don't have a full grasp of the source code and how everything works, if this would have unexpected consequences, e.g. in an aggregated result somewhere in the code. But a quick and brute test where I added a new option `--ignore-path` similar to how coverage targets are defined:

```
@Option(name: [.customLong("ignore-path")], help: "Specify file paths that should be ignored. You can use more than one --ignore-path option to specify a list of paths to ignore.")
var ignorePaths: [String] = []
```

And simply doing this in the coverage converters when `coverageJson.files` are iterated:
```
if ignorePaths.first(where: { file.contains($0)} ) != nil { continue }
```

Does the trick for me, then I'm able to specify a path, e.g. `--ignore-path .derivedData` to skip them from the output.

**Comment by a7ex** [comment]
Hi Martin,
thx for the suggestion. I will look into it and come back to you with answers or a PR :-)
However, xcresultparser is not responsible for the size of the xcresult bundle. It just parses what it finds there. You will need to adjust the settings in your app to not run tests on dependencies or count the dependencies into coverage. Not only that will make your xcresult bundle smaller, but also save time and resources to not create that data in the first place.

**Comment by a7ex** [comment]
I see now. The "coverage targets option" is only relevant, when creating a coverage report, but you are not creating a coverage report. You need the -c or --coverage option, to create a coverage report in the first place.
But yes, I see that the constraint to certain targets, doesn't happen for sonarqube- or cobertura-format. I will look into that.

**Comment by a7ex** [comment]
I created a new version now with your suggestion of a new parameter to exclude files. However that doesn't work for all commands. For test results for example I do not get a path. Concerning the target filter: it also only works, where xcresulttool gives us the information about the target. Which is not the case for the coverage info.
Nonetheless I hope the new release 1.8.0 can solve your problem. Nonetheless you might want to consider not running tests or gathering code coverage for targets, which you are not interested in, in the first place. That saves time and yields a smaller xcresult file.
