### ISSUE TITLE
Malformed JSON

### ISSUE THREAD

**Issue by Brett-Best** [a7ex/xcresultparser#45]
https://github.com/a7ex/xcresultparser/commit/ad453c7ba7b60c4fef555d1bbbc5c6e287ddbf89#diff-4139343d767bb586c64ef9d8663b2435008b06fed6b319f00a9a35978e310e01R65 this appears to cause malformed JSON output. Perhaps using the OSLog APIs would be better? Alternatively require an output file path.

```swift
private extension Set<String> {
    func isPathExcluded(_ path: String) -> Bool {
        print("Checking path: \(path)") // <----------------- this is the problem
        for excludedPath in self where path.contains(excludedPath) {
            return true
        }
        return false
    }
}
```

**Comment by a7ex** [comment]
Can you try now? I created a 1.8.1 where I fixed the issue
