### ISSUE TITLE
Slow performance when parsing test executions with --project-root

### ISSUE THREAD

**Issue by grant-mccarriagher** [a7ex/xcresultparser#46]
First of all, thanks for the tool, it works great. We are having one issue though, which is that when using a command like this, for generating test executions in XML:

`xcresultparser -o xml --project-root "$(pwd -P)" ./ios-unit-tests/Logs/Test/*.xcresult > ./reports/test_results.xml`

the command takes upwards of 8-10 minutes to complete (compared to just seconds without the `project-root` argument). I see that the command is making synchronous `grep` commands, which is probably where the bottleneck is, but I'm a little out of my depth in Swift for investigating what a possible improvement might be (making all the grep calls concurrently? generating an index of the xcresult folder first and searching that?).

Would love if this time could be shaved down a bit, let me know if you need any further info. Thanks!

**Comment by a7ex** [comment]
Odd... I have never noticed, nor have I been told, that --project-root slows down the execution so badly. Will look into it...

**Comment by a7ex** [comment]
I think you pinpointed it with your suspicion, that it might have to do with the `grep` command being in use.
That should be solvable by creating an index of suitable files beforehand.
I am still investigating other solutions to solve the problem, I can't believe, that there is no filename association for the test classes. It's not very "smart" of the xcresultparser tool at the moment to search the contents of each file over and over to map test class names to filenames... :-(

**Comment by grant-mccarriagher** [comment]
@a7ex Thanks so much for the quick fix, 10 minutes was reduced down to 9 seconds!
